global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Argentini.Sfumato.Entities;
global using Argentini.Sfumato.Extensions;

global using CliWrap;
global using Mapster;
global using Microsoft.Extensions.ObjectPool;
